paths:
    verticals:          './vert'
    registry:           './registry'
    compiled-corpora:   './manatee'
tools:
    unitok:             ''
    sentence-tagger:    ''
    desamb:             ''
    treetagger:         ''
    treetagger-en:      ''


