paths:
    verticals:          './vert'
    registry:           './registry'
    compiled-corpora:   './manatee'
tools:
    desamb:             ''
    treetagger:         ''
    unitok:             ''


