corpus-name:                'wiki_{lang}'
sample-corpus-name:         'wiki_{lang}{size}'
extensions:
    compressed-dump:        'dump.xml.bz2'
    uncompressed-dump:      'dump.xml'
    prevertical:            'prevert'
    vertical:               'vert'
